# 进程与线程

## 概述

进程是一种对运行中的程序的抽象，引入这个抽象之后每一个程序都认为它自己独占CPU。

## Linux上的进程操作

当fork刚刚调用完成时，两个进程的**内存、寄存器、程序计数器等状态**都是完全一致的，因为子进程会获得父进程的一个完全相同的拷贝，包括PCB中包含的打开的文件、寄存器和内存状态等内容；但是它们是两个完全独立的两个进程，拥有不同的PID与虚拟内存空间，在fork完成后他们会各自独立执行，互不干扰。正因为他们是两个独立的进程，他们的执行顺序完全取决于调度器的决策。

要重点理解的是刚刚调用完fork时，存在两个完全相同的进程，它们的代码段就是父进程的代码段。

在文件描述符（或者叫打开文件对象）里面会使用偏移量记录当前的进程读取到的某一个文件的某个位置。在fork时，子进程会获得与父进程一模一样的fd表，所以会指向相同的文件抽象，与父进程使用相同的偏移量。

在Linux中，第一个进程由操作系统创建，该进程特定且唯一，操作系统中所有后来的进程都由该进程产生。

为什么要使用fork创建进程呢？一个原因应该是从父进程哪里继承得到一些状态。

在进程地址空间中，一部分虚拟内存（比如共享代码库和代码段）是只读的，不需要对它们进行拷贝，而是在多个进程之间共享。



## 线程崩溃会导致进程崩溃

线程的一个缺点：
当进程中的一个线程崩溃的时候，会导致其所属进程的所有线程都崩溃，也即是说整个进程崩溃。这个情况在C\C++语言中成立；

线程崩溃后，OS通过给进程发送信号来使进程崩溃。进程也可以定义对应的信号处理函数来捕获对应的信号，自己控制是否让进程崩溃。

```C++
// 如果线程是因为非法访问内存引起的崩溃，那么进程一定会崩溃。在进程中，各个线程共享相同的地址空间，
// 线程对某个地址的非法访问可能会导致内存中的数据存在错误，这可能会影响到其他线程。OS会认为这会导致
// 一系列严重的后果，于是会让整个进程崩溃。

// 这段代码是一个线程访问了只读内存之后整个进程崩溃的情况,程序遇到的错误是bus error
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

char *s = "hello world";
pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;

void* thread_func(void *arg) {
    printf("thread_func: %s\n", s);
    s[2] = 'c';
    printf("thread_func: success\n");
    return NULL;
}

int main() {
   
    // 向只读内存写入数据，崩溃
    pthread_t tid;
    int err = pthread_create(&tid, NULL, thread_func, NULL);
    if (err != 0) {
        printf("pthread_create error: %s\n", strerror(err));
        exit(1);
    }
    // pthread_join(tid, NULL);
    sleep(1);
    printf("main: %s\n", s); 

}
```

```C++
// 这段代码是一个线程访问了没有权限访问的地方空间(本例中是内核空间)从而导致整个进程崩溃的情况,程序遇到的错误是segmentation fault
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <pthread.h> // macos上似乎不需要在编译时指定-lpthread

void* thread_func(void *arg) {
    int *p = (int *)0xC0000000FFFFFFFF;
    *p = 10;
    return NULL;
}

int main() {
   
    // 向只读内存写入数据，崩溃
    pthread_t tid;
    int err = pthread_create(&tid, NULL, thread_func, NULL);
    if (err != 0) {
        printf("pthread_create error: %s\n", strerror(err));
        exit(1);
    }
    
    sleep(1);
    printf("main: child run correctly\n"); 

}
```

```C++
// 同样是遇到了线程崩溃的情况，这个地方通过自定义信号处理函数来捕获对应的信号，做一些自己的逻辑处理
// 之后再让整个进程退出
#include <stdio.h>
#include <signal.h>
#include <stdlib.h>

// 自定义信号处理函数，处理自定义逻辑后再调用 exit 退出
void sigHandler(int sig) {
    printf("Signal %d catched!\n", sig);
    exit(sig);
}

int main(void) {
    // 注册信号处理函数 
    signal(SIGSEGV, sigHandler);
    int *p = (int *)0xC0000fff;
    *p = 10; // 针对不属于进程的内核空间写入数据，崩溃
}
```